# fly.toml app configuration file generated for shoper-billing-api-cat-3591 on 2024-12-05T09:50:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shoper-billing-api-cat-3591'
primary_region = 'waw'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "1024mb"
