# fly.toml app configuration file generated for webhook-api-little-meadow-5277 on 2024-12-06T11:59:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webhook-api-little-meadow-5277'
primary_region = 'waw'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "1024mb"
